import { useState, useMemo } from 'react';
import { Copy, Check, Hash } from 'lucide-react';
import type { DailyTaskInstance, DailyLogAnnotation, DailyAttendance } from '../types';
import type { IpmSprayLog, PlantMortalityLog } from '../types';

interface RoomActivity {
  roomName: string;
  tasksDone: number;
  tasksTotal: number;
  taskTypes: string[];
  laborHours: number;
  laborCost: number;
}

interface SlackPreviewProps {
  date: string;
  tasks: DailyTaskInstance[];
  annotations: DailyLogAnnotation[];
  attendance: DailyAttendance[];
  sprayLogs: IpmSprayLog[];
  mortalityLogs: PlantMortalityLog[];
  roomActivity: RoomActivity[];
  roomLookup: Record<string, string>;
  totalLaborCost: number;
}

const TASK_TYPE_LABELS: Record<string, string> = {
  ipm_spray: 'IPM Spray',
  defoliation: 'Defoliation',
  transplant: 'Transplant',
  cleaning: 'Cleaning',
  harvest: 'Harvest',
  batch_tank_mix: 'Batch Tank Mix',
  saturation_check: 'Saturation Check',
  irrigation_audit: 'Irrigation Audit',
  scouting: 'Scouting',
  training: 'Training',
  clone_cutting: 'Clone Cutting',
  maintenance: 'Maintenance',
  concentrate_mix: 'Concentrate Mix',
  custom: 'Custom',
};

function formatSlackDate(date: string): string {
  const d = new Date(date + 'T12:00:00');
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' });
}

export function DigestSlackPreview({
  date,
  tasks,
  annotations,
  attendance,
  sprayLogs,
  mortalityLogs,
  roomActivity,
  roomLookup,
  totalLaborCost,
}: SlackPreviewProps) {
  const [sections, setSections] = useState({
    taskSummary: true,
    roomBreakdown: true,
    laborCosts: true,
    annotations: true,
    alerts: true,
  });
  const [channel, setChannel] = useState('#cultivation-daily');
  const [copied, setCopied] = useState(false);

  const completed = tasks.filter((t) => t.status === 'completed').length;
  const total = tasks.length;
  const carryForward = tasks.filter((t) => t.status === 'carry_forward');
  const totalHours = attendance.reduce((sum, a) => sum + (a.hours_worked ?? 0), 0);
  const criticalAnnotations = annotations.filter((a) => a.severity === 'critical');

  const message = useMemo(() => {
    const lines: string[] = [];

    lines.push(`*CULT Daily Digest — ${formatSlackDate(date)}*`);
    lines.push('');

    if (sections.taskSummary) {
      lines.push('*Task Summary*');
      lines.push(`  Completed: ${completed} of ${total}`);
      if (carryForward.length > 0) {
        lines.push(`  Carry-Forward: ${carryForward.length}`);
        carryForward.forEach((t) => {
          const room = roomLookup[t.room_id] ?? t.room_id;
          lines.push(`    -> ${room}: ${TASK_TYPE_LABELS[t.task_type] ?? t.task_type}`);
        });
      }
      lines.push('');
    }

    if (sections.roomBreakdown && roomActivity.length > 0) {
      lines.push('*Room Breakdown*');
      roomActivity.forEach((r) => {
        const pct = r.tasksTotal > 0 ? Math.round((r.tasksDone / r.tasksTotal) * 100) : 0;
        const types = r.taskTypes.map((t) => TASK_TYPE_LABELS[t] ?? t).join(', ');
        lines.push(`  ${r.roomName}: ${r.tasksDone}/${r.tasksTotal} (${pct}%) — ${types}`);
      });
      lines.push('');
    }

    if (sections.laborCosts) {
      lines.push('*Labor*');
      lines.push(`  Workers: ${attendance.filter((a) => a.is_present).length}  |  Hours: ${totalHours.toFixed(1)}  |  Cost: $${totalLaborCost.toFixed(0)}`);
      lines.push('');
    }

    if (sections.alerts) {
      const hasAlerts = mortalityLogs.length > 0 || sprayLogs.length > 0 || criticalAnnotations.length > 0;
      if (hasAlerts) {
        lines.push('*Alerts*');
        mortalityLogs.forEach((m) => {
          const room = roomLookup[m.room_id] ?? m.room_id;
          lines.push(`  [MORTALITY] ${room}: ${m.quantity} plant(s) — ${m.cause ?? 'unknown cause'}`);
        });
        sprayLogs.forEach((s) => {
          const room = roomLookup[s.room_id] ?? s.room_id;
          lines.push(`  [SPRAY] ${room}: ${s.product_name} (${s.target_pest ?? 'general'})`);
        });
        criticalAnnotations.forEach((a) => {
          const room = roomLookup[a.room_id] ?? 'General';
          lines.push(`  [CRITICAL] ${room}: ${a.title}`);
        });
        lines.push('');
      }
    }

    if (sections.annotations && annotations.length > 0) {
      lines.push('*Notes*');
      annotations.forEach((a) => {
        const room = a.room_id ? (roomLookup[a.room_id] ?? '') : '';
        const prefix = room ? `${room}: ` : '';
        lines.push(`  ${prefix}${a.title}`);
      });
      lines.push('');
    }

    lines.push('— Generated by CULT Ops');
    return lines.join('\n');
  }, [date, tasks, annotations, attendance, sprayLogs, mortalityLogs, roomActivity, roomLookup, totalLaborCost, sections, completed, total, carryForward, totalHours, criticalAnnotations]);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(message);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard may be blocked */
    }
  }

  function toggleSection(key: keyof typeof sections) {
    setSections((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-4 flex-wrap">
        <div className="flex items-center gap-2">
          <Hash className="w-4 h-4 text-cult-text-muted" />
          <input
            type="text"
            value={channel}
            onChange={(e) => setChannel(e.target.value)}
            className="rounded-md bg-cult-surface border border-cult-border text-cult-text-primary text-sm px-3 py-1.5 w-52 focus:outline-none focus:border-cult-text-secondary"
          />
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-3 py-1.5 text-sm rounded-cult border border-cult-border text-cult-text-secondary hover:text-cult-text-primary hover:border-cult-border-strong transition-colors"
        >
          {copied ? <Check className="w-4 h-4 text-cult-success" /> : <Copy className="w-4 h-4" />}
          {copied ? 'Copied' : 'Copy to Clipboard'}
        </button>
        <button
          disabled
          className="px-3 py-1.5 text-sm rounded-cult bg-cult-border text-cult-text-muted cursor-not-allowed"
        >
          Post to Slack
        </button>
      </div>

      <div className="flex flex-wrap gap-3">
        {([
          ['taskSummary', 'Task Summary'],
          ['roomBreakdown', 'Room Breakdown'],
          ['laborCosts', 'Labor Costs'],
          ['annotations', 'Annotations'],
          ['alerts', 'Alerts'],
        ] as [keyof typeof sections, string][]).map(([key, label]) => (
          <label key={key} className="flex items-center gap-2 text-sm text-cult-text-secondary cursor-pointer select-none">
            <input
              type="checkbox"
              checked={sections[key]}
              onChange={() => toggleSection(key)}
              className="rounded border-cult-border accent-cult-accent"
            />
            {label}
          </label>
        ))}
      </div>

      <div className="rounded-lg border border-cult-border bg-cult-surface p-5 font-mono text-sm text-cult-text-secondary whitespace-pre-wrap leading-relaxed max-h-[500px] overflow-y-auto">
        {message}
      </div>
    </div>
  );
}
