import { useState, useEffect, useCallback, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  AlertTriangle,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronRight,
  Clock,
  Eye,
  Filter,
  Loader2,
  MapPin,
  RefreshCw,
  Search,
  Sparkles,
  TrendingUp,
  Users,
  X,
  Zap,
} from 'lucide-react';
import { LoadingSpinner } from '@/shared/components';
import { getTaskSummary, completeTask, dismissTask, runTaskEngine } from '../services/crm.service';
import type { CRMTask, TaskType, TaskPriority } from '../types/crm.types';

interface AutomatedTaskEngineProps {}

type StatusFilter = 'open' | 'completed' | 'auto_closed' | 'all';
type TypeFilter = TaskType | 'all';
type SourceFilter = 'auto' | 'manual' | 'all';
type SortField = 'due_date' | 'priority' | 'created_at' | 'customer_name';
type SortDir = 'asc' | 'desc';

const TASK_TYPE_LABELS: Record<TaskType, string> = {
  reorder_reminder: 'Reorder',
  visit_overdue: 'Visit Overdue',
  visit_follow_up: 'Follow-Up',
  prospect_advancement: 'Prospect',
  general: 'General',
};

const TASK_TYPE_ICONS: Record<TaskType, typeof Bell> = {
  reorder_reminder: RefreshCw,
  visit_overdue: MapPin,
  visit_follow_up: Calendar,
  prospect_advancement: TrendingUp,
  general: Bell,
};

const PRIORITY_COLORS: Record<TaskPriority, string> = {
  high: 'bg-cult-danger-muted text-cult-danger border-cult-danger/30',
  medium: 'bg-cult-warning-muted text-cult-warning border-cult-warning/30',
  low: 'bg-cult-500/20 text-cult-400 border-cult-500/30',
};

const PRIORITY_SORT_ORDER: Record<TaskPriority, number> = {
  high: 3,
  medium: 2,
  low: 1,
};

export function AutomatedTaskEngine({}: AutomatedTaskEngineProps) {
  const navigate = useNavigate();
  const [tasks, setTasks] = useState<CRMTask[]>([]);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('open');
  const [typeFilter, setTypeFilter] = useState<TypeFilter>('all');
  const [sourceFilter, setSourceFilter] = useState<SourceFilter>('all');
  const [search, setSearch] = useState('');
  const [sortField, setSortField] = useState<SortField>('priority');
  const [sortDir, setSortDir] = useState<SortDir>('desc');
  const [actionLoadingId, setActionLoadingId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    const filters: Record<string, string> = {};
    if (statusFilter !== 'all') filters.status = statusFilter;
    if (typeFilter !== 'all') filters.taskType = typeFilter;
    if (sourceFilter !== 'all') filters.triggerSource = sourceFilter;
    const { data } = await getTaskSummary(Object.keys(filters).length > 0 ? filters : undefined);
    setTasks(data);
    setLoading(false);
  }, [statusFilter, typeFilter, sourceFilter]);

  useEffect(() => { load(); }, [load]);

  const handleComplete = async (id: string) => {
    setActionLoadingId(id);
    await completeTask(id);
    setTasks((prev) => prev.filter((t) => t.id !== id));
    setActionLoadingId(null);
  };

  const handleDismiss = async (id: string) => {
    setActionLoadingId(id);
    await dismissTask(id);
    setTasks((prev) => prev.filter((t) => t.id !== id));
    setActionLoadingId(null);
  };

  const handleRunEngine = async () => {
    setRunning(true);
    await runTaskEngine();
    await load();
    setRunning(false);
  };

  // ── Aggregates ───────────────────────────────────────────────
  const stats = useMemo(() => {
    const open = tasks.filter((t) => t.status === 'open');
    return {
      total: open.length,
      highPriority: open.filter((t) => t.priority === 'high').length,
      overdue: open.filter((t) => t.is_overdue).length,
      byType: Object.entries(TASK_TYPE_LABELS).map(([key, label]) => ({
        type: key as TaskType,
        label,
        count: open.filter((t) => t.task_type === key).length,
      })).filter((t) => t.count > 0),
      autoGenerated: open.filter((t) => t.trigger_source === 'auto').length,
    };
  }, [tasks]);

  // ── Filtered + sorted ────────────────────────────────────────
  const filteredTasks = useMemo(() => {
    let result = [...tasks];

    if (search) {
      const q = search.toLowerCase();
      result = result.filter(
        (t) =>
          t.title.toLowerCase().includes(q) ||
          t.customer_name?.toLowerCase().includes(q) ||
          t.description?.toLowerCase().includes(q)
      );
    }

    result.sort((a, b) => {
      const dir = sortDir === 'asc' ? 1 : -1;
      switch (sortField) {
        case 'due_date':
          return dir * ((a.due_date || '').localeCompare(b.due_date || ''));
        case 'priority':
          return dir * ((PRIORITY_SORT_ORDER[a.priority] || 0) - (PRIORITY_SORT_ORDER[b.priority] || 0));
        case 'created_at':
          return dir * ((a.created_at || '').localeCompare(b.created_at || ''));
        case 'customer_name':
          return dir * ((a.customer_name || '').localeCompare(b.customer_name || ''));
        default:
          return 0;
      }
    });

    return result;
  }, [tasks, search, sortField, sortDir]);

  const toggleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortField(field);
      setSortDir(field === 'priority' ? 'desc' : 'asc');
    }
  };

  if (loading) return <LoadingSpinner />;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-purple-500/10">
            <Zap className="w-6 h-6 text-purple-400" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-cult-text-primary">Automated Task Engine</h1>
            <p className="text-sm text-cult-400">
              AI-generated tasks from account health, visit cadence, and prospect data
            </p>
          </div>
        </div>
        <button
          onClick={handleRunEngine}
          disabled={running}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-purple-500/20 text-purple-300 hover:bg-purple-500/30 border border-purple-500/30 transition-colors disabled:opacity-50"
        >
          {running ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Sparkles className="w-4 h-4" />
          )}
          {running ? 'Running...' : 'Run Now'}
        </button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-cult-800 rounded-cult border border-cult-700 p-4">
          <div className="flex items-center gap-2 text-cult-400 text-xs font-medium mb-1">
            <Clock className="w-3.5 h-3.5" />
            OPEN TASKS
          </div>
          <div className="text-2xl font-bold text-cult-text-primary">{stats.total}</div>
          <div className="text-xs text-cult-500 mt-1">{stats.autoGenerated} auto-generated</div>
        </div>
        <div className="bg-cult-800 rounded-cult border border-cult-700 p-4">
          <div className="flex items-center gap-2 text-cult-danger text-xs font-medium mb-1">
            <AlertTriangle className="w-3.5 h-3.5" />
            HIGH PRIORITY
          </div>
          <div className="text-2xl font-bold text-cult-danger">{stats.highPriority}</div>
          <div className="text-xs text-cult-500 mt-1">need immediate action</div>
        </div>
        <div className="bg-cult-800 rounded-cult border border-cult-700 p-4">
          <div className="flex items-center gap-2 text-cult-warning text-xs font-medium mb-1">
            <AlertTriangle className="w-3.5 h-3.5" />
            OVERDUE
          </div>
          <div className="text-2xl font-bold text-cult-warning">{stats.overdue}</div>
          <div className="text-xs text-cult-500 mt-1">past due date</div>
        </div>
        <div className="bg-cult-800 rounded-cult border border-cult-700 p-4">
          <div className="flex items-center gap-2 text-cult-400 text-xs font-medium mb-1">
            <Sparkles className="w-3.5 h-3.5" />
            BY TYPE
          </div>
          <div className="space-y-1 mt-1">
            {stats.byType.length === 0 && (
              <div className="text-sm text-cult-500">No open tasks</div>
            )}
            {stats.byType.map((t) => {
              const Icon = TASK_TYPE_ICONS[t.type];
              return (
                <div key={t.type} className="flex items-center gap-2 text-xs">
                  <Icon className="w-3 h-3 text-cult-400" />
                  <span className="text-cult-300">{t.label}</span>
                  <span className="ml-auto text-cult-text-primary font-medium">{t.count}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-cult-500" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search tasks or customers..."
            className="w-full pl-9 pr-3 py-2 text-sm bg-cult-800 border border-cult-700 rounded-lg text-cult-text-primary placeholder:text-cult-500 focus:outline-none focus:border-cult-500"
          />
        </div>

        <div className="flex items-center gap-1 bg-cult-800 rounded-lg border border-cult-700 p-0.5">
          {(['open', 'completed', 'auto_closed', 'all'] as StatusFilter[]).map((s) => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              className={`px-3 py-1.5 text-xs font-medium rounded-md transition-colors ${
                statusFilter === s
                  ? 'bg-cult-700 text-cult-text-primary'
                  : 'text-cult-400 hover:text-cult-300'
              }`}
            >
              {s === 'auto_closed' ? 'Dismissed' : s.charAt(0).toUpperCase() + s.slice(1)}
            </button>
          ))}
        </div>

        <select
          value={typeFilter}
          onChange={(e) => setTypeFilter(e.target.value as TypeFilter)}
          className="px-3 py-2 text-xs bg-cult-800 border border-cult-700 rounded-lg text-cult-300 focus:outline-none"
        >
          <option value="all">All Types</option>
          {Object.entries(TASK_TYPE_LABELS).map(([key, label]) => (
            <option key={key} value={key}>{label}</option>
          ))}
        </select>

        <select
          value={sourceFilter}
          onChange={(e) => setSourceFilter(e.target.value as SourceFilter)}
          className="px-3 py-2 text-xs bg-cult-800 border border-cult-700 rounded-lg text-cult-300 focus:outline-none"
        >
          <option value="all">All Sources</option>
          <option value="auto">Auto-Generated</option>
          <option value="manual">Manual</option>
        </select>

        <button
          onClick={load}
          className="p-2 text-cult-400 hover:text-cult-300 transition-colors"
          title="Refresh"
        >
          <RefreshCw className="w-4 h-4" />
        </button>
      </div>

      {/* Task List */}
      {filteredTasks.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-cult-500">
          <CheckCircle2 className="w-12 h-12 mb-3 opacity-30" />
          <p className="text-sm font-medium">No tasks match your filters</p>
          <p className="text-xs mt-1">Try adjusting your search or filter criteria</p>
        </div>
      ) : (
        <div className="space-y-2">
          {/* Sort header */}
          <div className="grid grid-cols-12 gap-2 px-4 py-2 text-xs font-medium text-cult-500 uppercase tracking-wider">
            <div className="col-span-1">Type</div>
            <div
              className="col-span-4 cursor-pointer hover:text-cult-300 flex items-center gap-1"
              onClick={() => toggleSort('customer_name')}
            >
              Task {sortField === 'customer_name' && (sortDir === 'asc' ? '↑' : '↓')}
            </div>
            <div
              className="col-span-2 cursor-pointer hover:text-cult-300 flex items-center gap-1"
              onClick={() => toggleSort('priority')}
            >
              Priority {sortField === 'priority' && (sortDir === 'asc' ? '↑' : '↓')}
            </div>
            <div
              className="col-span-2 cursor-pointer hover:text-cult-300 flex items-center gap-1"
              onClick={() => toggleSort('due_date')}
            >
              Due {sortField === 'due_date' && (sortDir === 'asc' ? '↑' : '↓')}
            </div>
            <div className="col-span-1">Source</div>
            <div className="col-span-2 text-right">Actions</div>
          </div>

          {filteredTasks.map((task) => {
            const TypeIcon = TASK_TYPE_ICONS[task.task_type] || Bell;
            const isActioning = actionLoadingId === task.id;
            const isOpen = task.status === 'open';

            return (
              <div
                key={task.id}
                className={`grid grid-cols-12 gap-2 items-center px-4 py-3 rounded-cult border transition-colors ${
                  task.is_overdue
                    ? 'bg-cult-danger/5 border-cult-danger/20 hover:bg-cult-danger/10'
                    : 'bg-cult-800 border-cult-700 hover:bg-cult-750'
                }`}
              >
                {/* Type icon */}
                <div className="col-span-1">
                  <div className="p-1.5 rounded-lg bg-cult-700/50 w-fit" title={TASK_TYPE_LABELS[task.task_type]}>
                    <TypeIcon className="w-4 h-4 text-cult-300" />
                  </div>
                </div>

                {/* Title + customer */}
                <div className="col-span-4 min-w-0">
                  <div className="text-sm font-medium text-cult-text-primary truncate">{task.title}</div>
                  <div className="flex items-center gap-2 mt-0.5">
                    <button
                      onClick={() => navigate(`/crm-account-detail/${task.customer_id}`)}
                      className="text-xs text-cult-400 hover:text-purple-400 truncate transition-colors"
                    >
                      {task.customer_name}
                    </button>
                    {task.dispensary_code && (
                      <span className="text-xs text-cult-500 font-mono">{task.dispensary_code}</span>
                    )}
                  </div>
                </div>

                {/* Priority */}
                <div className="col-span-2">
                  <span className={`inline-flex items-center px-2 py-0.5 text-xs font-medium rounded-full border ${PRIORITY_COLORS[task.priority]}`}>
                    {task.priority}
                  </span>
                  {task.is_overdue && (
                    <span className="ml-1 text-xs text-cult-danger font-medium">
                      {task.days_overdue}d overdue
                    </span>
                  )}
                </div>

                {/* Due date */}
                <div className="col-span-2 text-xs text-cult-400">
                  {task.due_date ? new Date(task.due_date + 'T00:00:00').toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                  }) : '—'}
                </div>

                {/* Source */}
                <div className="col-span-1">
                  {task.trigger_source === 'auto' ? (
                    <span className="inline-flex items-center gap-1 text-xs text-purple-400 bg-purple-500/10 px-1.5 py-0.5 rounded">
                      <Zap className="w-2.5 h-2.5" /> auto
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 text-xs text-cult-400 bg-cult-700/50 px-1.5 py-0.5 rounded">
                      <Users className="w-2.5 h-2.5" /> manual
                    </span>
                  )}
                </div>

                {/* Actions */}
                <div className="col-span-2 flex items-center justify-end gap-1">
                  {isOpen && !isActioning && (
                    <>
                      <button
                        onClick={() => handleComplete(task.id)}
                        className="p-1.5 rounded-lg text-cult-success hover:bg-cult-success/10 transition-colors"
                        title="Mark complete"
                      >
                        <Check className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDismiss(task.id)}
                        className="p-1.5 rounded-lg text-cult-500 hover:bg-cult-700 hover:text-cult-300 transition-colors"
                        title="Dismiss"
                      >
                        <X className="w-4 h-4" />
                      </button>
                    </>
                  )}
                  {isActioning && (
                    <Loader2 className="w-4 h-4 text-cult-400 animate-spin" />
                  )}
                  {!isOpen && (
                    <span className="text-xs text-cult-500 capitalize">
                      {task.status === 'auto_closed' ? 'dismissed' : task.status}
                    </span>
                  )}
                  <button
                    onClick={() => navigate(`/crm-account-detail/${task.customer_id}`)}
                    className="p-1.5 rounded-lg text-cult-500 hover:text-cult-300 hover:bg-cult-700 transition-colors"
                    title="View account"
                  >
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
